{
  "category": "Control",
  "name": "THROWIFNOT",
  "tests": [
    {
      "name": "Without throw exception",
      "script": [
        "PUSH0",
        "PUSH1",
        "THROWIFNOT"
      ],
      "steps": [
        {
          "actions": [
            "stepInto",
            "stepInto",
            "stepInto"
          ],
          "result": {
            "state": "BREAK",
            "invocationStack": [
              {
                "instructionPointer": 3,
                "nextInstruction": "RET"
              }
            ]
          }
        },
        {
          "actions": [
            "stepInto"
          ],
          "result": {
            "state": "HALT"
          }
        }
      ]
    },
    {
      "name": "Throw exception (with PUSH)",
      "script": [
        "PUSH0",
        "THROWIFNOT"
      ],
      "steps": [
        {
          "actions": [
            "execute"
          ],
          "result": {
            "state": "FAULT"
          }
        }
      ]
    },
    {
      "name": "Throw exception (without PUSH - FAULT)",
      "script": [
        "THROWIFNOT"
      ],
      "steps": [
        {
          "actions": [
            "execute"
          ],
          "result": {
            "state": "FAULT"
          }
        }
      ]
    }
  ]
}
