{
  "category": "Control",
  "name": "THROWIF",
  "tests": [
    {
      "name": "Without throw exception",
      "script": [
        "PUSH0",
        "PUSH0",
        "THROWIF"
      ],
      "steps": [
        {
          "actions": [
            "stepInto",
            "stepInto"
          ],
          "result": {
            "state": "BREAK",
            "invocationStack": [
              {
                "instructionPointer": 2,
                "nextInstruction": "THROWIF",
                "evaluationStack": [
                  {
                    "type": "integer",
                    "value": 0
                  },
                  {
                    "type": "integer",
                    "value": 0
                  }
                ]
              }
            ]
          }
        },
        {
          "actions": [
            "execute"
          ],
          "result": {
            "state": "HALT"
          }
        }
      ]
    },
    {
      "name": "Throw exception (with PUSH)",
      "script": [
        "PUSH0",
        "PUSH1",
        "THROWIF"
      ],
      "steps": [
        {
          "actions": [
            "execute"
          ],
          "result": {
            "state": "FAULT"
          }
        }
      ]
    },
    {
      "name": "Throw exception (without PUSH - FAULT)",
      "script": [
        "THROWIF"
      ],
      "steps": [
        {
          "actions": [
            "execute"
          ],
          "result": {
            "state": "FAULT"
          }
        }
      ]
    }
  ]
}
